### ISSUE TITLE
error with unirest

### ISSUE THREAD

**Issue by rohitchangediya** [vittominacori/changelly-php#2]
Fatal error: Uncaught Error: Call to undefined function Unirest\curl_init() in /var/www/html/api/changelly-php/vendor/mashape/unirest-php/src/Unirest/Request.php:396 Stack trace: #0 /var/www/html/api/changelly-php/vendor/mashape/unirest-php/src/Unirest/Request.php(292): Unirest\Request::send('POST', 'https://api.cha...', '{"jsonrpc":"2.0...', Array, NULL, NULL) #1 /var/www/html/api/changelly-php/src/Changelly.php(142): Unirest\Request::post('https://api.cha...', Array, '{"jsonrpc":"2.0...') #2 /var/www/html/api/changelly-php/src/Changelly.php(46): Changelly\Changelly->post('getCurrencies') #3 /var/www/html/api/changelly-php/sample.php(12): Changelly\Changelly->getCurrencies() #4 {main} thrown in /var/www/html/api/changelly-php/vendor/mashape/unirest-php/src/Unirest/Request.php on line 396

**Comment by vittominacori** [comment]
Have you manually removed Unirest as dependency?

Try to reinstall package with `composer require vittominacori/changelly-php`

**Comment by rohitchangediya** [comment]
got resolved, thanks for prompt reply :)
